Route11_Script:
	jp EnableAutoTextBoxDrawing

Route11_TextPointers:
	def_text_pointers
	dw_const Route11DiglettsCaveSignText, TEXT_ROUTE11_DIGLETTSCAVE_SIGN

Route11DiglettsCaveSignText:
	text_far _Route11DiglettsCaveSignText
	text_end
