Route22_Script:
	jp EnableAutoTextBoxDrawing

Route22_TextPointers:
	def_text_pointers
	dw_const Route22PokemonLeagueSignText, TEXT_ROUTE22_POKEMON_LEAGUE_SIGN

Route22PokemonLeagueSignText:
	text_far _Route22PokemonLeagueSignText
	text_end
