SECTION "Pics 1", ROMX

MoltresPicFront::    INCBIN "gfx/pokemon/moltres/front.pic"
MoltresPicBack::     INCBIN "gfx/pokemon/moltres/back.pic"

TentacoolPicFront::  INCBIN "gfx/pokemon/tentacool/front.pic"
TentacoolPicBack::   INCBIN "gfx/pokemon/tentacool/back.pic"
ScytherPicFront::    INCBIN "gfx/pokemon/scyther/front.pic"
ScytherPicBack::     INCBIN "gfx/pokemon/scyther/back.pic"
StaryuPicFront::     INCBIN "gfx/pokemon/staryu/front.pic"
StaryuPicBack::      INCBIN "gfx/pokemon/staryu/back.pic"
BlastoisePicFront::  INCBIN "gfx/pokemon/blastoise/front.pic"
BlastoisePicBack::   INCBIN "gfx/pokemon/blastoise/back.pic"
PinsirPicFront::     INCBIN "gfx/pokemon/pinsir/front.pic"
PinsirPicBack::      INCBIN "gfx/pokemon/pinsir/back.pic"
TangelaPicFront::    INCBIN "gfx/pokemon/tangela/front.pic"
TangelaPicBack::     INCBIN "gfx/pokemon/tangela/back.pic"

JolteonPicFront::    INCBIN "gfx/pokemon/jolteon/front.pic"
JolteonPicBack::     INCBIN "gfx/pokemon/jolteon/back.pic"
VaporeonPicFront::   INCBIN "gfx/pokemon/vaporeon/front.pic"
VaporeonPicBack::    INCBIN "gfx/pokemon/vaporeon/back.pic"
MachopPicFront::     INCBIN "gfx/pokemon/machop/front.pic"
MachopPicBack::      INCBIN "gfx/pokemon/machop/back.pic"
ZubatPicFront::      INCBIN "gfx/pokemon/zubat/front.pic"
ZubatPicBack::       INCBIN "gfx/pokemon/zubat/back.pic"
EkansPicFront::      INCBIN "gfx/pokemon/ekans/front.pic"
EkansPicBack::       INCBIN "gfx/pokemon/ekans/back.pic"
ParasPicFront::      INCBIN "gfx/pokemon/paras/front.pic"
ParasPicBack::       INCBIN "gfx/pokemon/paras/back.pic"
PoliwhirlPicFront::  INCBIN "gfx/pokemon/poliwhirl/front.pic"
PoliwhirlPicBack::   INCBIN "gfx/pokemon/poliwhirl/back.pic"
PoliwrathPicFront::  INCBIN "gfx/pokemon/poliwrath/front.pic"
PoliwrathPicBack::   INCBIN "gfx/pokemon/poliwrath/back.pic"
WeedlePicFront::     INCBIN "gfx/pokemon/weedle/front.pic"
WeedlePicBack::      INCBIN "gfx/pokemon/weedle/back.pic"
KakunaPicFront::     INCBIN "gfx/pokemon/kakuna/front.pic"
KakunaPicBack::      INCBIN "gfx/pokemon/kakuna/back.pic"
BeedrillPicFront::   INCBIN "gfx/pokemon/beedrill/front.pic"
BeedrillPicBack::    INCBIN "gfx/pokemon/beedrill/back.pic"


SECTION "Pics 2", ROMX

HaunterPicFront::    INCBIN "gfx/pokemon/haunter/front.pic"
HaunterPicBack::     INCBIN "gfx/pokemon/haunter/back.pic"
AbraPicFront::       INCBIN "gfx/pokemon/abra/front.pic"
AbraPicBack::        INCBIN "gfx/pokemon/abra/back.pic"
AlakazamPicFront::   INCBIN "gfx/pokemon/alakazam/front.pic"
AlakazamPicBack::    INCBIN "gfx/pokemon/alakazam/back.pic"
PidgeottoPicFront::  INCBIN "gfx/pokemon/pidgeotto/front.pic"
PidgeottoPicBack::   INCBIN "gfx/pokemon/pidgeotto/back.pic"
PidgeotPicFront::    INCBIN "gfx/pokemon/pidgeot/front.pic"
PidgeotPicBack::     INCBIN "gfx/pokemon/pidgeot/back.pic"
StarmiePicFront::    INCBIN "gfx/pokemon/starmie/front.pic"
StarmiePicBack::     INCBIN "gfx/pokemon/starmie/back.pic"
RedPicBack::         INCBIN "gfx/gstrainers/redb.pic"
OldManPicBack::      INCBIN "gfx/gstrainers/oldmanb.pic"

GastlyPicFront::     INCBIN "gfx/pokemon/gastly/front.pic"
GastlyPicBack::      INCBIN "gfx/pokemon/gastly/back.pic"
VileplumePicFront::  INCBIN "gfx/pokemon/vileplume/front.pic"
VileplumePicBack::   INCBIN "gfx/pokemon/vileplume/back.pic"


SECTION "Pics 3", ROMX

; Removed 'mon sprites from here


SECTION "Pics 4", ROMX

; Removed 'mon sprites from here


SECTION "Pics 5", ROMX

; Removed 'mon sprites from here


SECTION "Trainer Pics", ROMX

TrainerPics::
YoungsterPic::     INCBIN "gfx/gstrainers/youngster.pic"
BugCatcherPic::    INCBIN "gfx/gstrainers/bugcatcher.pic"
LassPic::          INCBIN "gfx/gstrainers/lass.pic"
SailorPic::        INCBIN "gfx/gstrainers/sailor.pic"
JrTrainerMPic::    INCBIN "gfx/gstrainers/jr.trainerm.pic"
JrTrainerFPic::    INCBIN "gfx/gstrainers/jr.trainerf.pic"
PokemaniacPic::    INCBIN "gfx/gstrainers/pokemaniac.pic"
SuperNerdPic::     INCBIN "gfx/gstrainers/supernerd.pic"
HikerPic::         INCBIN "gfx/gstrainers/hiker.pic"
BikerPic::         INCBIN "gfx/gstrainers/biker.pic"
BurglarPic::       INCBIN "gfx/gstrainers/burglar.pic"
EngineerPic::      INCBIN "gfx/gstrainers/engineer.pic"
FisherPic::        INCBIN "gfx/gstrainers/fisher.pic"
SwimmerPic::       INCBIN "gfx/gstrainers/swimmer.pic"
CueBallPic::       INCBIN "gfx/gstrainers/cueball.pic"
GamblerPic::       INCBIN "gfx/gstrainers/gambler.pic"
BeautyPic::        INCBIN "gfx/gstrainers/beauty.pic"
PsychicPic::       INCBIN "gfx/gstrainers/psychic.pic"
RockerPic::        INCBIN "gfx/gstrainers/rocker.pic"
JugglerPic::       INCBIN "gfx/gstrainers/juggler.pic"
TamerPic::         INCBIN "gfx/gstrainers/tamer.pic"
BirdKeeperPic::    INCBIN "gfx/gstrainers/birdkeeper.pic"
BlackbeltPic::     INCBIN "gfx/gstrainers/blackbelt.pic"
Rival1Pic::        INCBIN "gfx/gstrainers/rival1.pic"
ProfOakPic::       INCBIN "gfx/gstrainers/prof.oak.pic"
ChiefPic::
ScientistPic::     INCBIN "gfx/gstrainers/scientist.pic"
GiovanniPic::      INCBIN "gfx/gstrainers/giovanni.pic"
RocketPic::        INCBIN "gfx/gstrainers/rocket.pic"
CooltrainerMPic::  INCBIN "gfx/gstrainers/cooltrainerm.pic"
CooltrainerFPic::  INCBIN "gfx/gstrainers/cooltrainerf.pic"
BrunoPic::         INCBIN "gfx/gstrainers/bruno.pic"
BrockPic::         INCBIN "gfx/gstrainers/brock.pic"
MistyPic::         INCBIN "gfx/gstrainers/misty.pic"
LtSurgePic::       INCBIN "gfx/gstrainers/lt.surge.pic"
ErikaPic::         INCBIN "gfx/gstrainers/erika.pic"
KogaPic::          INCBIN "gfx/gstrainers/koga.pic"
BlainePic::        INCBIN "gfx/gstrainers/blaine.pic"
SabrinaPic::       INCBIN "gfx/gstrainers/sabrina.pic"
GentlemanPic::     INCBIN "gfx/gstrainers/gentleman.pic"
Rival2Pic::        INCBIN "gfx/gstrainers/rival2.pic"
Rival3Pic::        INCBIN "gfx/gstrainers/rival3.pic"
LoreleiPic::       INCBIN "gfx/gstrainers/lorelei.pic"
ChannelerPic::     INCBIN "gfx/gstrainers/channeler.pic"
AgathaPic::        INCBIN "gfx/gstrainers/agatha.pic"
LancePic::         INCBIN "gfx/gstrainers/lance.pic"

SECTION "Trainer Pics 2", ROMX

SwimmerFPic::      INCBIN "gfx/gstrainers/swimmer_f.pic" ; unused
SwimmermPc::       INCBIN "gfx/gstrainers/swimmer_m.pic" ; unused
MikanPic::         INCBIN "gfx/gstrainers/mikan.pic" ; unused


; Inserted pokemon images go here

SECTION "Pics 7", ROMX

GrowlithePicFront::   INCBIN "gfx/pokemon/growlithe/front.pic"
GrowlithePicBack::    INCBIN "gfx/pokemon/growlithe/back.pic"
OnixPicFront::        INCBIN "gfx/pokemon/onix/front.pic"
OnixPicBack::         INCBIN "gfx/pokemon/onix/back.pic"
FearowPicFront::      INCBIN "gfx/pokemon/fearow/front.pic"
FearowPicBack::       INCBIN "gfx/pokemon/fearow/back.pic"
PidgeyPicFront::      INCBIN "gfx/pokemon/pidgey/front.pic"
PidgeyPicBack::       INCBIN "gfx/pokemon/pidgey/back.pic"
SlowpokePicFront::    INCBIN "gfx/pokemon/slowpoke/front.pic"
SlowpokePicBack::     INCBIN "gfx/pokemon/slowpoke/back.pic"
KadabraPicFront::     INCBIN "gfx/pokemon/kadabra/front.pic"
KadabraPicBack::      INCBIN "gfx/pokemon/kadabra/back.pic"
GravelerPicFront::    INCBIN "gfx/pokemon/graveler/front.pic"
GravelerPicBack::     INCBIN "gfx/pokemon/graveler/back.pic"
ChanseyPicFront::     INCBIN "gfx/pokemon/chansey/front.pic"
ChanseyPicBack::      INCBIN "gfx/pokemon/chansey/back.pic"
MachokePicFront::     INCBIN "gfx/pokemon/machoke/front.pic"
MachokePicBack::      INCBIN "gfx/pokemon/machoke/back.pic"
MrMimePicFront::      INCBIN "gfx/pokemon/mr.mime/front.pic"
MrMimePicBack::       INCBIN "gfx/pokemon/mr.mime/back.pic"
HitmonleePicFront::   INCBIN "gfx/pokemon/hitmonlee/front.pic"
HitmonleePicBack::    INCBIN "gfx/pokemon/hitmonlee/back.pic"
HitmonchanPicFront::  INCBIN "gfx/pokemon/hitmonchan/front.pic"
HitmonchanPicBack::   INCBIN "gfx/pokemon/hitmonchan/back.pic"
ArbokPicFront::       INCBIN "gfx/pokemon/arbok/front.pic"
ArbokPicBack::        INCBIN "gfx/pokemon/arbok/back.pic"
ParasectPicFront::    INCBIN "gfx/pokemon/parasect/front.pic"
ParasectPicBack::     INCBIN "gfx/pokemon/parasect/back.pic"


SECTION "Pics 8", ROMX

PsyduckPicFront::     INCBIN "gfx/pokemon/psyduck/front.pic"
PsyduckPicBack::      INCBIN "gfx/pokemon/psyduck/back.pic"
DrowzeePicFront::     INCBIN "gfx/pokemon/drowzee/front.pic"
DrowzeePicBack::      INCBIN "gfx/pokemon/drowzee/back.pic"
GolemPicFront::       INCBIN "gfx/pokemon/golem/front.pic"
GolemPicBack::        INCBIN "gfx/pokemon/golem/back.pic"
MagmarPicFront::      INCBIN "gfx/pokemon/magmar/front.pic"
MagmarPicBack::       INCBIN "gfx/pokemon/magmar/back.pic"
ElectabuzzPicFront::  INCBIN "gfx/pokemon/electabuzz/front.pic"
ElectabuzzPicBack::   INCBIN "gfx/pokemon/electabuzz/back.pic"
MagnetonPicFront::    INCBIN "gfx/pokemon/magneton/front.pic"
MagnetonPicBack::     INCBIN "gfx/pokemon/magneton/back.pic"
KoffingPicFront::     INCBIN "gfx/pokemon/koffing/front.pic"
KoffingPicBack::      INCBIN "gfx/pokemon/koffing/back.pic"
MankeyPicFront::      INCBIN "gfx/pokemon/mankey/front.pic"
MankeyPicBack::       INCBIN "gfx/pokemon/mankey/back.pic"
SeelPicFront::        INCBIN "gfx/pokemon/seel/front.pic"
SeelPicBack::         INCBIN "gfx/pokemon/seel/back.pic"
DiglettPicFront::     INCBIN "gfx/pokemon/diglett/front.pic"
DiglettPicBack::      INCBIN "gfx/pokemon/diglett/back.pic"
TaurosPicFront::      INCBIN "gfx/pokemon/tauros/front.pic"
TaurosPicBack::       INCBIN "gfx/pokemon/tauros/back.pic"
RhydonPicFront::      INCBIN "gfx/pokemon/rhydon/front.pic"
RhydonPicBack::       INCBIN "gfx/pokemon/rhydon/back.pic"
KangaskhanPicFront::  INCBIN "gfx/pokemon/kangaskhan/front.pic"
KangaskhanPicBack::   INCBIN "gfx/pokemon/kangaskhan/back.pic"
NidoranMPicFront::    INCBIN "gfx/pokemon/nidoranm/front.pic"
NidoranMPicBack::     INCBIN "gfx/pokemon/nidoranm/back.pic"
ClefairyPicFront::    INCBIN "gfx/pokemon/clefairy/front.pic"
ClefairyPicBack::     INCBIN "gfx/pokemon/clefairy/back.pic"
SpearowPicFront::     INCBIN "gfx/pokemon/spearow/front.pic"
SpearowPicBack::      INCBIN "gfx/pokemon/spearow/back.pic"
VoltorbPicFront::     INCBIN "gfx/pokemon/voltorb/front.pic"
VoltorbPicBack::      INCBIN "gfx/pokemon/voltorb/back.pic"



SECTION "Pics 9", ROMX

NidokingPicFront::    INCBIN "gfx/pokemon/nidoking/front.pic"
NidokingPicBack::     INCBIN "gfx/pokemon/nidoking/back.pic"
SlowbroPicFront::     INCBIN "gfx/pokemon/slowbro/front.pic"
SlowbroPicBack::      INCBIN "gfx/pokemon/slowbro/back.pic"
IvysaurPicFront::     INCBIN "gfx/pokemon/ivysaur/front.pic"
IvysaurPicBack::      INCBIN "gfx/pokemon/ivysaur/back.pic"
ExeggutorPicFront::   INCBIN "gfx/pokemon/exeggutor/front.pic"
ExeggutorPicBack::    INCBIN "gfx/pokemon/exeggutor/back.pic"
LickitungPicFront::   INCBIN "gfx/pokemon/lickitung/front.pic"
LickitungPicBack::    INCBIN "gfx/pokemon/lickitung/back.pic"
ExeggcutePicFront::   INCBIN "gfx/pokemon/exeggcute/front.pic"
ExeggcutePicBack::    INCBIN "gfx/pokemon/exeggcute/back.pic"
GrimerPicFront::      INCBIN "gfx/pokemon/grimer/front.pic"
GrimerPicBack::       INCBIN "gfx/pokemon/grimer/back.pic"
GengarPicFront::      INCBIN "gfx/pokemon/gengar/front.pic"
GengarPicBack::       INCBIN "gfx/pokemon/gengar/back.pic"
NidoranFPicFront::    INCBIN "gfx/pokemon/nidoranf/front.pic"
NidoranFPicBack::     INCBIN "gfx/pokemon/nidoranf/back.pic"
NidoqueenPicFront::   INCBIN "gfx/pokemon/nidoqueen/front.pic"
NidoqueenPicBack::    INCBIN "gfx/pokemon/nidoqueen/back.pic"
CubonePicFront::      INCBIN "gfx/pokemon/cubone/front.pic"
CubonePicBack::       INCBIN "gfx/pokemon/cubone/back.pic"
RhyhornPicFront::     INCBIN "gfx/pokemon/rhyhorn/front.pic"
RhyhornPicBack::      INCBIN "gfx/pokemon/rhyhorn/back.pic"
LaprasPicFront::      INCBIN "gfx/pokemon/lapras/front.pic"
LaprasPicBack::       INCBIN "gfx/pokemon/lapras/back.pic"
ArcaninePicFront::    INCBIN "gfx/pokemon/arcanine/front.pic"
ArcaninePicBack::     INCBIN "gfx/pokemon/arcanine/back.pic"
GyaradosPicFront::    INCBIN "gfx/pokemon/gyarados/front.pic"
GyaradosPicBack::     INCBIN "gfx/pokemon/gyarados/back.pic"
ShellderPicFront::    INCBIN "gfx/pokemon/shellder/front.pic"
ShellderPicBack::     INCBIN "gfx/pokemon/shellder/back.pic"



SECTION "Pics 10", ROMX

ArticunoPicFront::    INCBIN "gfx/pokemon/articuno/front.pic"
ArticunoPicBack::     INCBIN "gfx/pokemon/articuno/back.pic"
ZapdosPicFront::      INCBIN "gfx/pokemon/zapdos/front.pic"
ZapdosPicBack::       INCBIN "gfx/pokemon/zapdos/back.pic"
DittoPicFront::       INCBIN "gfx/pokemon/ditto/front.pic"
DittoPicBack::        INCBIN "gfx/pokemon/ditto/back.pic"
MeowthPicFront::      INCBIN "gfx/pokemon/meowth/front.pic"
MeowthPicBack::       INCBIN "gfx/pokemon/meowth/back.pic"
KrabbyPicFront::      INCBIN "gfx/pokemon/krabby/front.pic"
KrabbyPicBack::       INCBIN "gfx/pokemon/krabby/back.pic"
VulpixPicFront::      INCBIN "gfx/pokemon/vulpix/front.pic"
VulpixPicBack::       INCBIN "gfx/pokemon/vulpix/back.pic"
NinetalesPicFront::   INCBIN "gfx/pokemon/ninetales/front.pic"
NinetalesPicBack::    INCBIN "gfx/pokemon/ninetales/back.pic"
PikachuPicFront::     INCBIN "gfx/pokemon/pikachu/front.pic"
PikachuPicBack::      INCBIN "gfx/pokemon/pikachu/back.pic"
RaichuPicFront::      INCBIN "gfx/pokemon/raichu/front.pic"
RaichuPicBack::       INCBIN "gfx/pokemon/raichu/back.pic"
DratiniPicFront::     INCBIN "gfx/pokemon/dratini/front.pic"
DratiniPicBack::      INCBIN "gfx/pokemon/dratini/back.pic"
DragonairPicFront::   INCBIN "gfx/pokemon/dragonair/front.pic"
DragonairPicBack::    INCBIN "gfx/pokemon/dragonair/back.pic"
KabutoPicFront::      INCBIN "gfx/pokemon/kabuto/front.pic"
KabutoPicBack::       INCBIN "gfx/pokemon/kabuto/back.pic"
KabutopsPicFront::    INCBIN "gfx/pokemon/kabutops/front.pic"
KabutopsPicBack::     INCBIN "gfx/pokemon/kabutops/back.pic"
HorseaPicFront::      INCBIN "gfx/pokemon/horsea/front.pic"
HorseaPicBack::       INCBIN "gfx/pokemon/horsea/back.pic"
SeadraPicFront::      INCBIN "gfx/pokemon/seadra/front.pic"
SeadraPicBack::       INCBIN "gfx/pokemon/seadra/back.pic"
SandshrewPicFront::   INCBIN "gfx/pokemon/sandshrew/front.pic"
SandshrewPicBack::    INCBIN "gfx/pokemon/sandshrew/back.pic"
SandslashPicFront::   INCBIN "gfx/pokemon/sandslash/front.pic"
SandslashPicBack::    INCBIN "gfx/pokemon/sandslash/back.pic"



SECTION "Pics 11", ROMX

OmanytePicFront::     INCBIN "gfx/pokemon/omanyte/front.pic"
OmanytePicBack::      INCBIN "gfx/pokemon/omanyte/back.pic"
OmastarPicFront::     INCBIN "gfx/pokemon/omastar/front.pic"
OmastarPicBack::      INCBIN "gfx/pokemon/omastar/back.pic"
JigglypuffPicFront::  INCBIN "gfx/pokemon/jigglypuff/front.pic"
JigglypuffPicBack::   INCBIN "gfx/pokemon/jigglypuff/back.pic"
WigglytuffPicFront::  INCBIN "gfx/pokemon/wigglytuff/front.pic"
WigglytuffPicBack::   INCBIN "gfx/pokemon/wigglytuff/back.pic"
EeveePicFront::       INCBIN "gfx/pokemon/eevee/front.pic"
EeveePicBack::        INCBIN "gfx/pokemon/eevee/back.pic"
FlareonPicFront::     INCBIN "gfx/pokemon/flareon/front.pic"
FlareonPicBack::      INCBIN "gfx/pokemon/flareon/back.pic"
DodrioPicFront::      INCBIN "gfx/pokemon/dodrio/front.pic"
DodrioPicBack::       INCBIN "gfx/pokemon/dodrio/back.pic"
PrimeapePicFront::    INCBIN "gfx/pokemon/primeape/front.pic"
PrimeapePicBack::     INCBIN "gfx/pokemon/primeape/back.pic"
DugtrioPicFront::     INCBIN "gfx/pokemon/dugtrio/front.pic"
DugtrioPicBack::      INCBIN "gfx/pokemon/dugtrio/back.pic"
VenomothPicFront::    INCBIN "gfx/pokemon/venomoth/front.pic"
VenomothPicBack::     INCBIN "gfx/pokemon/venomoth/back.pic"
DewgongPicFront::     INCBIN "gfx/pokemon/dewgong/front.pic"
DewgongPicBack::      INCBIN "gfx/pokemon/dewgong/back.pic"


SECTION "Pics 12", ROMX

CaterpiePicFront::    INCBIN "gfx/pokemon/caterpie/front.pic"
CaterpiePicBack::     INCBIN "gfx/pokemon/caterpie/back.pic"
MetapodPicFront::     INCBIN "gfx/pokemon/metapod/front.pic"
MetapodPicBack::      INCBIN "gfx/pokemon/metapod/back.pic"
ButterfreePicFront::  INCBIN "gfx/pokemon/butterfree/front.pic"
ButterfreePicBack::   INCBIN "gfx/pokemon/butterfree/back.pic"
MachampPicFront::     INCBIN "gfx/pokemon/machamp/front.pic"
MachampPicBack::      INCBIN "gfx/pokemon/machamp/back.pic"
GolduckPicFront::     INCBIN "gfx/pokemon/golduck/front.pic"
GolduckPicBack::      INCBIN "gfx/pokemon/golduck/back.pic"
HypnoPicFront::       INCBIN "gfx/pokemon/hypno/front.pic"
HypnoPicBack::        INCBIN "gfx/pokemon/hypno/back.pic"
GolbatPicFront::      INCBIN "gfx/pokemon/golbat/front.pic"
GolbatPicBack::       INCBIN "gfx/pokemon/golbat/back.pic"
MewtwoPicFront::      INCBIN "gfx/pokemon/mewtwo/front.pic"
MewtwoPicBack::       INCBIN "gfx/pokemon/mewtwo/back.pic"
SnorlaxPicFront::     INCBIN "gfx/pokemon/snorlax/front.pic"
SnorlaxPicBack::      INCBIN "gfx/pokemon/snorlax/back.pic"
MagikarpPicFront::    INCBIN "gfx/pokemon/magikarp/front.pic"
MagikarpPicBack::     INCBIN "gfx/pokemon/magikarp/back.pic"
MukPicFront::         INCBIN "gfx/pokemon/muk/front.pic"
MukPicBack::          INCBIN "gfx/pokemon/muk/back.pic"
KinglerPicFront::     INCBIN "gfx/pokemon/kingler/front.pic"
KinglerPicBack::      INCBIN "gfx/pokemon/kingler/back.pic"
CloysterPicFront::    INCBIN "gfx/pokemon/cloyster/front.pic"
CloysterPicBack::     INCBIN "gfx/pokemon/cloyster/back.pic"
ElectrodePicFront::   INCBIN "gfx/pokemon/electrode/front.pic"
ElectrodePicBack::    INCBIN "gfx/pokemon/electrode/back.pic"
ClefablePicFront::    INCBIN "gfx/pokemon/clefable/front.pic"
ClefablePicBack::     INCBIN "gfx/pokemon/clefable/back.pic"
WeezingPicFront::     INCBIN "gfx/pokemon/weezing/front.pic"
WeezingPicBack::      INCBIN "gfx/pokemon/weezing/back.pic"
PersianPicFront::     INCBIN "gfx/pokemon/persian/front.pic"
PersianPicBack::      INCBIN "gfx/pokemon/persian/back.pic"

SECTION "Pics 13", ROMX

BulbasaurPicFront::   INCBIN "gfx/pokemon/bulbasaur/front.pic"
BulbasaurPicBack::    INCBIN "gfx/pokemon/bulbasaur/back.pic"
VenusaurPicFront::    INCBIN "gfx/pokemon/venusaur/front.pic"
VenusaurPicBack::     INCBIN "gfx/pokemon/venusaur/back.pic"
TentacruelPicFront::  INCBIN "gfx/pokemon/tentacruel/front.pic"
TentacruelPicBack::   INCBIN "gfx/pokemon/tentacruel/back.pic"
GoldeenPicFront::     INCBIN "gfx/pokemon/goldeen/front.pic"
GoldeenPicBack::      INCBIN "gfx/pokemon/goldeen/back.pic"
SeakingPicFront::     INCBIN "gfx/pokemon/seaking/front.pic"
SeakingPicBack::      INCBIN "gfx/pokemon/seaking/back.pic"
PonytaPicFront::      INCBIN "gfx/pokemon/ponyta/front.pic"
RapidashPicFront::    INCBIN "gfx/pokemon/rapidash/front.pic"
PonytaPicBack::       INCBIN "gfx/pokemon/ponyta/back.pic"
RapidashPicBack::     INCBIN "gfx/pokemon/rapidash/back.pic"
RattataPicFront::     INCBIN "gfx/pokemon/rattata/front.pic"
RattataPicBack::      INCBIN "gfx/pokemon/rattata/back.pic"
RaticatePicFront::    INCBIN "gfx/pokemon/raticate/front.pic"
RaticatePicBack::     INCBIN "gfx/pokemon/raticate/back.pic"
NidorinoPicFront::    INCBIN "gfx/pokemon/nidorino/front.pic"
NidorinoPicBack::     INCBIN "gfx/pokemon/nidorino/back.pic"
NidorinaPicFront::    INCBIN "gfx/pokemon/nidorina/front.pic"
NidorinaPicBack::     INCBIN "gfx/pokemon/nidorina/back.pic"
GeodudePicFront::     INCBIN "gfx/pokemon/geodude/front.pic"
GeodudePicBack::      INCBIN "gfx/pokemon/geodude/back.pic"
PorygonPicFront::     INCBIN "gfx/pokemon/porygon/front.pic"
PorygonPicBack::      INCBIN "gfx/pokemon/porygon/back.pic"
AerodactylPicFront::  INCBIN "gfx/pokemon/aerodactyl/front.pic"
AerodactylPicBack::   INCBIN "gfx/pokemon/aerodactyl/back.pic"
MagnemitePicFront::   INCBIN "gfx/pokemon/magnemite/front.pic"
MagnemitePicBack::    INCBIN "gfx/pokemon/magnemite/back.pic"
CharmanderPicFront::  INCBIN "gfx/pokemon/charmander/front.pic"
CharmanderPicBack::   INCBIN "gfx/pokemon/charmander/back.pic"
SquirtlePicFront::    INCBIN "gfx/pokemon/squirtle/front.pic"
SquirtlePicBack::     INCBIN "gfx/pokemon/squirtle/back.pic"
CharmeleonPicFront::  INCBIN "gfx/pokemon/charmeleon/front.pic"
CharmeleonPicBack::   INCBIN "gfx/pokemon/charmeleon/back.pic"

SECTION "Pics 14", ROMX

WartortlePicFront::   INCBIN "gfx/pokemon/wartortle/front.pic"
WartortlePicBack::    INCBIN "gfx/pokemon/wartortle/back.pic"
CharizardPicFront::   INCBIN "gfx/pokemon/charizard/front.pic"
CharizardPicBack::    INCBIN "gfx/pokemon/charizard/back.pic"
FossilKabutopsPic::   INCBIN "gfx/pokemon/front/fossilkabutops.pic"
FossilAerodactylPic:: INCBIN "gfx/pokemon/front/fossilaerodactyl.pic"
GhostPic::            INCBIN "gfx/battle/ghost.pic"
OddishPicFront::      INCBIN "gfx/pokemon/oddish/front.pic"
OddishPicBack::       INCBIN "gfx/pokemon/oddish/back.pic"
GloomPicFront::       INCBIN "gfx/pokemon/gloom/front.pic"
GloomPicBack::        INCBIN "gfx/pokemon/gloom/back.pic"
BellsproutPicFront::  INCBIN "gfx/pokemon/bellsprout/front.pic"
BellsproutPicBack::   INCBIN "gfx/pokemon/bellsprout/back.pic"
WeepinbellPicFront::  INCBIN "gfx/pokemon/weepinbell/front.pic"
WeepinbellPicBack::   INCBIN "gfx/pokemon/weepinbell/back.pic"
VictreebelPicFront::  INCBIN "gfx/pokemon/victreebel/front.pic"
VictreebelPicBack::   INCBIN "gfx/pokemon/victreebel/back.pic"

MewPicFront::         INCBIN "gfx/pokemon/mew/front.pic"
MewPicBack::          INCBIN "gfx/pokemon/mew/back.pic"

FarfetchdPicFront::   INCBIN "gfx/pokemon/farfetchd/front.pic"
FarfetchdPicBack::    INCBIN "gfx/pokemon/farfetchd/back.pic"
VenonatPicFront::     INCBIN "gfx/pokemon/venonat/front.pic"
VenonatPicBack::      INCBIN "gfx/pokemon/venonat/back.pic"
DragonitePicFront::   INCBIN "gfx/pokemon/dragonite/front.pic"
DragonitePicBack::    INCBIN "gfx/pokemon/dragonite/back.pic"
DoduoPicFront::       INCBIN "gfx/pokemon/doduo/front.pic"
DoduoPicBack::        INCBIN "gfx/pokemon/doduo/back.pic"
PoliwagPicFront::     INCBIN "gfx/pokemon/poliwag/front.pic"
PoliwagPicBack::      INCBIN "gfx/pokemon/poliwag/back.pic"
JynxPicFront::        INCBIN "gfx/pokemon/jynx/front.pic"
JynxPicBack::         INCBIN "gfx/pokemon/jynx/back.pic"
MarowakPicFront::     INCBIN "gfx/pokemon/marowak/front.pic"
MarowakPicBack::      INCBIN "gfx/pokemon/marowak/back.pic"
HappaPicFront::       INCBIN "gfx/pokemon/happa/front.pic"
HappaPicBack::        INCBIN "gfx/pokemon/happa/back.pic"
HanamoguraPicFront::  INCBIN "gfx/pokemon/hanamogura/front.pic"
HanamoguraPicBack::   INCBIN "gfx/pokemon/hanamogura/back.pic"
HanaryuPicFront::     INCBIN "gfx/pokemon/hanaryu/front.pic"
HanaryuPicBack::      INCBIN "gfx/pokemon/hanaryu/back.pic"
HonogumaPicFront::    INCBIN "gfx/pokemon/honoguma/front.pic"
HonogumaPicBack::     INCBIN "gfx/pokemon/honoguma/back.pic"
BorubeaPicFront::     INCBIN "gfx/pokemon/borubea/front.pic"
BorubeaPicBack::      INCBIN "gfx/pokemon/borubea/back.pic"
DainabeaPicFront::    INCBIN "gfx/pokemon/dainabea/front.pic"
DainabeaPicBack::     INCBIN "gfx/pokemon/dainabea/back.pic"
KurusuPicFront::      INCBIN "gfx/pokemon/kurusu/front.pic"
KurusuPicBack::       INCBIN "gfx/pokemon/kurusu/back.pic"
AkuaPicFront::        INCBIN "gfx/pokemon/akua/front.pic"
AkuaPicBack::         INCBIN "gfx/pokemon/akua/back.pic"
AkueriaPicFront::     INCBIN "gfx/pokemon/akueria/front.pic"
AkueriaPicBack::      INCBIN "gfx/pokemon/akueria/back.pic"
