; INPUTS - Mon DVs in de, species in wGenderTemp
; OUTPUT - Mon's gender in wGenderTemp
GetMonGender::
	ld hl, MonGenderRatios
	ld a, [wGenderTemp]
	dec a
	ld c, a
	ld b, 0
	add hl, bc ; hl now points to the species gender ratio

; Attack DV
	ld a, [de]
	and $f0
	ld b, a
; Speed DV
	inc de
	ld a, [de]
	and $f0
	swap a
; Put them together
	or b
	ld b, a ; b now has the combined DVs

; Get the gender ratio
	ld a, [hl]

; Check for always one or another
	cp NO_GENDER
	jr z, .genderless

	cp FEMALE_ONLY
	jr z, .female

	and a ; MALE_ONLY
	jr z, .male

; Compare the ratio to the value we found earlier
	cp b
	jr c, .male

.female
	ld a, FEMALE
	jr .done
.male
	ld a, MALE
	jr .done
.genderless
	ld a, GENDERLESS
.done
	ld [wGenderTemp], a
	ret

MonGenderRatios:
	db SAME_BOTH_GENDERS ; RHYDON
	db FEMALE_ONLY       ; KANGASKHAN
	db MALE_ONLY         ; NIDORAN_M
	db FEMALE_75_PERCENT ; CLEFAIRY
	db SAME_BOTH_GENDERS ; SPEAROW
	db NO_GENDER         ; VOLTORB
	db MALE_ONLY         ; NIDOKING
	db SAME_BOTH_GENDERS ; SLOWBRO
	db MALE_88_PERCENT   ; IVYSAUR
	db SAME_BOTH_GENDERS ; EXEGGUTOR
	db SAME_BOTH_GENDERS ; LICKITUNG
	db SAME_BOTH_GENDERS ; EXEGGCUTE
	db SAME_BOTH_GENDERS ; GRIMER
	db SAME_BOTH_GENDERS ; GENGAR
	db FEMALE_ONLY       ; NIDORAN_F
	db FEMALE_ONLY       ; NIDOQUEEN
	db SAME_BOTH_GENDERS ; CUBONE
	db SAME_BOTH_GENDERS ; RHYHORN
	db SAME_BOTH_GENDERS ; LAPRAS
	db MALE_75_PERCENT   ; ARCANINE
	db NO_GENDER         ; MEW
	db SAME_BOTH_GENDERS ; GYARADOS
	db SAME_BOTH_GENDERS ; SHELLDER
	db SAME_BOTH_GENDERS ; TENTACOOL
	db SAME_BOTH_GENDERS ; GASTLY
	db SAME_BOTH_GENDERS ; SCYTHER
	db NO_GENDER         ; STARYU
	db MALE_88_PERCENT   ; BLASTOISE
	db SAME_BOTH_GENDERS ; PINSIR
	db SAME_BOTH_GENDERS ; TANGELA
	db MALE_88_PERCENT   ; HAPPA
	db MALE_88_PERCENT   ; HANAMOGURA
	db MALE_75_PERCENT   ; GROWLITHE
	db SAME_BOTH_GENDERS ; ONIX
	db SAME_BOTH_GENDERS ; FEAROW
	db SAME_BOTH_GENDERS ; PIDGEY
	db SAME_BOTH_GENDERS ; SLOWPOKE
	db MALE_75_PERCENT   ; KADABRA
	db SAME_BOTH_GENDERS ; GRAVELER
	db FEMALE_ONLY       ; CHANSEY
	db MALE_75_PERCENT   ; MACHOKE
	db NO_GENDER         ; MR_MIME
	db MALE_ONLY         ; HITMONLEE
	db MALE_ONLY         ; HITMONCHAN
	db SAME_BOTH_GENDERS ; ARBOK
	db SAME_BOTH_GENDERS ; PARASECT
	db SAME_BOTH_GENDERS ; PSYDUCK
	db SAME_BOTH_GENDERS ; DROWZEE
	db SAME_BOTH_GENDERS ; GOLEM
	db MALE_88_PERCENT   ; HANARYU
	db MALE_75_PERCENT   ; MAGMAR
	db MALE_88_PERCENT   ; HONOGUMA
	db MALE_75_PERCENT   ; ELECTABUZZ
	db NO_GENDER         ; MAGNETON
	db SAME_BOTH_GENDERS ; KOFFING
	db MALE_88_PERCENT   ; BORUBEA
	db SAME_BOTH_GENDERS ; MANKEY
	db SAME_BOTH_GENDERS ; SEEL
	db SAME_BOTH_GENDERS ; DIGLETT
	db MALE_ONLY         ; TAUROS
	db MALE_88_PERCENT   ; DAINABEA
	db FEMALE_75_PERCENT ; KURUSU
	db FEMALE_75_PERCENT ; AKUA
	db SAME_BOTH_GENDERS ; FARFETCHD
	db SAME_BOTH_GENDERS ; VENONAT
	db SAME_BOTH_GENDERS ; DRAGONITE
	db FEMALE_75_PERCENT ; AKUERIA
	db SAME_BOTH_GENDERS ; HOHO
	db SAME_BOTH_GENDERS ; BOBO
	db SAME_BOTH_GENDERS ; DODUO
	db SAME_BOTH_GENDERS ; POLIWAG
	db FEMALE_ONLY       ; JYNX
	db NO_GENDER         ; MOLTRES
	db NO_GENDER         ; ARTICUNO
	db NO_GENDER         ; ZAPDOS
	db NO_GENDER         ; DITTO
	db SAME_BOTH_GENDERS ; MEOWTH
	db SAME_BOTH_GENDERS ; KRABBY
	db SAME_BOTH_GENDERS ; PACHIME
	db SAME_BOTH_GENDERS ; MOKOKO
	db SAME_BOTH_GENDERS ; DENRYU
	db FEMALE_75_PERCENT ; VULPIX
	db FEMALE_75_PERCENT ; NINETALES
	db SAME_BOTH_GENDERS ; PIKACHU
	db SAME_BOTH_GENDERS ; RAICHU
	db FEMALE_75_PERCENT ; MIKON
	db SAME_BOTH_GENDERS ; MONJA
	db SAME_BOTH_GENDERS ; DRATINI
	db SAME_BOTH_GENDERS ; DRAGONAIR
	db MALE_88_PERCENT   ; KABUTO
	db MALE_88_PERCENT   ; KABUTOPS
	db SAME_BOTH_GENDERS ; HORSEA
	db SAME_BOTH_GENDERS ; SEADRA
	db SAME_BOTH_GENDERS ; JARANRA
	db SAME_BOTH_GENDERS ; HANEI
	db SAME_BOTH_GENDERS ; SANDSHREW
	db SAME_BOTH_GENDERS ; SANDSLASH
	db MALE_88_PERCENT   ; OMANYTE
	db MALE_88_PERCENT   ; OMASTAR
	db FEMALE_75_PERCENT ; JIGGLYPUFF
	db FEMALE_75_PERCENT ; WIGGLYTUFF
	db MALE_88_PERCENT   ; EEVEE
	db MALE_88_PERCENT   ; FLAREON
	db MALE_88_PERCENT   ; JOLTEON
	db MALE_88_PERCENT   ; VAPOREON
	db MALE_75_PERCENT   ; MACHOP
	db SAME_BOTH_GENDERS ; ZUBAT
	db SAME_BOTH_GENDERS ; EKANS
	db SAME_BOTH_GENDERS ; PARAS
	db SAME_BOTH_GENDERS ; POLIWHIRL
	db SAME_BOTH_GENDERS ; POLIWRATH
	db SAME_BOTH_GENDERS ; WEEDLE
	db SAME_BOTH_GENDERS ; KAKUNA
	db SAME_BOTH_GENDERS ; BEEDRILL
	db SAME_BOTH_GENDERS ; PUKU
	db SAME_BOTH_GENDERS ; DODRIO
	db SAME_BOTH_GENDERS ; PRIMEAPE
	db SAME_BOTH_GENDERS ; DUGTRIO
	db SAME_BOTH_GENDERS ; VENOMOTH
	db SAME_BOTH_GENDERS ; DEWGONG
	db SAME_BOTH_GENDERS ; SHIBIREFUGU
	db SAME_BOTH_GENDERS ; PICHU
	db SAME_BOTH_GENDERS ; CATERPIE
	db SAME_BOTH_GENDERS ; METAPOD
	db SAME_BOTH_GENDERS ; BUTTERFREE
	db MALE_75_PERCENT   ; MACHAMP
	db FEMALE_75_PERCENT ; PY
	db SAME_BOTH_GENDERS ; GOLDUCK
	db SAME_BOTH_GENDERS ; HYPNO
	db SAME_BOTH_GENDERS ; GOLBAT
	db NO_GENDER         ; MEWTWO
	db MALE_88_PERCENT   ; SNORLAX
	db SAME_BOTH_GENDERS ; MAGIKARP
	db FEMALE_75_PERCENT ; PUPURIN
	db SAME_BOTH_GENDERS ; MIZUO
	db SAME_BOTH_GENDERS ; MUK
	db SAME_BOTH_GENDERS ; NEITI
	db SAME_BOTH_GENDERS ; KINGLER
	db SAME_BOTH_GENDERS ; CLOYSTER
	db SAME_BOTH_GENDERS ; NEITIO
	db NO_GENDER         ; ELECTRODE
	db FEMALE_75_PERCENT ; CLEFABLE
	db SAME_BOTH_GENDERS ; WEEZING
	db SAME_BOTH_GENDERS ; PERSIAN
	db SAME_BOTH_GENDERS ; MAROWAK
	db SAME_BOTH_GENDERS ; GYOPIN
	db SAME_BOTH_GENDERS ; HAUNTER
	db MALE_75_PERCENT   ; ABRA
	db MALE_75_PERCENT   ; ALAKAZAM
	db SAME_BOTH_GENDERS ; PIDGEOTTO
	db SAME_BOTH_GENDERS ; PIDGEOT
	db NO_GENDER         ; STARMIE
	db MALE_88_PERCENT   ; BULBASAUR
	db MALE_88_PERCENT   ; VENUSAUR
	db SAME_BOTH_GENDERS ; TENTACRUEL
	db SAME_BOTH_GENDERS ; MARIRU
	db SAME_BOTH_GENDERS ; GOLDEEN
	db SAME_BOTH_GENDERS ; SEAKING
	db SAME_BOTH_GENDERS ; MANBO1
	db SAME_BOTH_GENDERS ; IKARI
	db SAME_BOTH_GENDERS ; GUROTESU
	db SAME_BOTH_GENDERS ; EKUSHINGU
	db SAME_BOTH_GENDERS ; PONYTA
	db SAME_BOTH_GENDERS ; RAPIDASH
	db SAME_BOTH_GENDERS ; RATTATA
	db SAME_BOTH_GENDERS ; RATICATE
	db MALE_ONLY         ; NIDORINO
	db FEMALE_ONLY       ; NIDORINA
	db SAME_BOTH_GENDERS ; GEODUDE
	db NO_GENDER         ; PORYGON
	db MALE_88_PERCENT   ; AERODACTYL
	db SAME_BOTH_GENDERS ; PARA
	db NO_GENDER         ; MAGNEMITE
	db SAME_BOTH_GENDERS ; KOKUMO
	db SAME_BOTH_GENDERS ; TSUHEDDO
	db MALE_88_PERCENT   ; CHARMANDER
	db MALE_88_PERCENT   ; SQUIRTLE
	db MALE_88_PERCENT   ; CHARMELEON
	db MALE_88_PERCENT   ; WARTORTLE
	db MALE_88_PERCENT   ; CHARIZARD
	db SAME_BOTH_GENDERS ; YOROIDORI
	db NO_GENDER         ; FOSSIL_KABUTOPS
	db NO_GENDER         ; FOSSIL_AERODACTYL
	db NO_GENDER         ; MON_GHOST
	db SAME_BOTH_GENDERS ; ODDISH
	db SAME_BOTH_GENDERS ; GLOOM
	db SAME_BOTH_GENDERS ; VILEPLUME
	db SAME_BOTH_GENDERS ; BELLSPROUT
	db SAME_BOTH_GENDERS ; WEEPINBELL
	db SAME_BOTH_GENDERS ; VICTREEBEL
	db NO_GENDER         ; ANIMON
	db SAME_BOTH_GENDERS ; HINAZU
	db SAME_BOTH_GENDERS ; SANI
	db SAME_BOTH_GENDERS ; PAON
	db SAME_BOTH_GENDERS ; DONFAN
	db SAME_BOTH_GENDERS ; TSUINZU
	db SAME_BOTH_GENDERS ; KIRINRIKI
	db SAME_BOTH_GENDERS ; PEINTA
	db SAME_BOTH_GENDERS ; KONYA
	db SAME_BOTH_GENDERS ; RINRIN
	db SAME_BOTH_GENDERS ; BERURUN
	db SAME_BOTH_GENDERS ; NYOROTONO
	db SAME_BOTH_GENDERS ; YADOKINGU
	db NO_GENDER         ; ANNON
	db SAME_BOTH_GENDERS ; REDIBA
	db SAME_BOTH_GENDERS ; MITSUBOSHI
	db SAME_BOTH_GENDERS ; PUCHIKON
	db MALE_88_PERCENT   ; EFI
	db MALE_88_PERCENT   ; BURAKKI
	db SAME_BOTH_GENDERS ; TABAN
	db SAME_BOTH_GENDERS ; BETOBEBI
	db SAME_BOTH_GENDERS ; TEPPOUO
	db SAME_BOTH_GENDERS ; OKUTAN
	db MALE_ONLY         ; GONGU
	db MALE_ONLY         ; KAPOERA
	db SAME_BOTH_GENDERS ; PUDI
	db SAME_BOTH_GENDERS ; HANEKO
	db SAME_BOTH_GENDERS ; POPONEKO
	db SAME_BOTH_GENDERS ; WATANEKO
	db SAME_BOTH_GENDERS ; BARIRINA
	db FEMALE_ONLY       ; RIPPU
	db MALE_75_PERCENT   ; BUBI
	db MALE_75_PERCENT   ; BUBYI
	db SAME_BOTH_GENDERS ; KIREIHANA
	db SAME_BOTH_GENDERS ; TSUBOMITTO
	db FEMALE_ONLY       ; MIRUTANKU
	db SAME_BOTH_GENDERS ; BOMUSHIKA
	db SAME_BOTH_GENDERS ; GIFUTO
	db SAME_BOTH_GENDERS ; KOTORA
	db SAME_BOTH_GENDERS ; RAITORA
	db SAME_BOTH_GENDERS ; MADAMU
	db SAME_BOTH_GENDERS ; NOROWARA
	db SAME_BOTH_GENDERS ; KYONPAN
	db SAME_BOTH_GENDERS ; YAMIKARASU
	db FEMALE_ONLY       ; HAPPII
	db SAME_BOTH_GENDERS ; SHIZASU
	db SAME_BOTH_GENDERS ; PURAKKUSU
	db SAME_BOTH_GENDERS ; DEBIRU
	db SAME_BOTH_GENDERS ; HERUGAA
	db SAME_BOTH_GENDERS ; URUFUMAN
	db SAME_BOTH_GENDERS ; WAURUFU
	db NO_GENDER         ; PORYGON2
	db SAME_BOTH_GENDERS ; NAMERU
	db SAME_BOTH_GENDERS ; HAGANEERU
	db SAME_BOTH_GENDERS ; KINGUDORA
	db NO_GENDER         ; RAI
	db NO_GENDER         ; EN
	db NO_GENDER         ; SUI
	db SAME_BOTH_GENDERS ; NYOORA
	db NO_GENDER         ; HOUOU
	db MALE_88_PERCENT   ; TOGEPI
	db SAME_BOTH_GENDERS ; BULU
	db SAME_BOTH_GENDERS ; TEIRU
	db SAME_BOTH_GENDERS ; RIIFI
